version: "3.9"
services:
  server:
    build: src/

    command: python ./main.py

    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: correlation_db
      MONGODB_HOSTNAME: mongodb
    volumes:
      - appdata:/var/www 
    depends_on:
       - mongodb

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: correlation_db
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
